name:           Bootstrap Brasil Blog
description:    Tradução do Blog Bootstrap Oficial pela comunidade Bootstrap Brasil..
url:            http://bootstrapbrasil.github.io/bootstrap-blog
baseurl: 		/bootstrap-blog

markdown:       kramdown
highlighter:    pygments
permalink:      pretty
paginate:       5
encoding:       UTF-8
future:         true

exclude:        ["README.md"]
